(function(){
  'use strict';
  var API='/__chord_editor__/';
  var onlineHost=location.hostname==='127.0.0.1'||location.hostname==='localhost';
  var managementEnabled=false,events=[],expanded=new Set(),action=null;
  var $=function(id){return document.getElementById(id);};
  var status=$('server-status'),label=$('server-label'),detail=$('server-detail'),check=$('check-server'),stop=$('stop-server'),shortcut=$('add-shortcut'),feedback=$('shortcut-feedback'),list=$('index-list'),count=$('index-count'),shutdownDialog=$('shutdown-dialog');
  var manager=$('manager-dialog'),form=$('manager-form'),fields=$('manager-fields'),managerError=$('manager-error'),managerConfirm=$('manager-confirm'),eventButton=$('create-event-menu'),eventMenu=$('event-menu');
  var icons={open:'<svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true"><path d="M14 3h7v7h-2V6.41l-9.29 9.3-1.42-1.42 9.3-9.29H14V3zM5 5h6v2H7v10h10v-4h2v6H5V5z"/></svg>',edit:'<svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true"><path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zm17.71-10.21a.996.996 0 0 0 0-1.41l-2.34-2.34a.996.996 0 0 0-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"/></svg>',more:'<svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true"><circle cx="5" cy="12" r="2"/><circle cx="12" cy="12" r="2"/><circle cx="19" cy="12" r="2"/></svg>'};

  function messageFrom(response,data){return data&&data.error&&data.error.message?data.error.message:'Erro HTTP '+response.status;}
  async function jsonRequest(path,options){var response=await fetch(API+path,Object.assign({cache:'no-store'},options));var text=await response.text(),data;try{data=JSON.parse(text);}catch(error){if(response.status===501)throw new Error('O servidor está desatualizado. Feche-o e abra novamente pelo atalho.');throw new Error('O servidor devolveu uma resposta inválida (HTTP '+response.status+').');}if(!response.ok)throw new Error(messageFrom(response,data));return data;}
  function body(value){return {headers:{'Content-Type':'application/json'},body:JSON.stringify(value)};}
  function setManagement(enabled){managementEnabled=enabled;document.querySelectorAll('.management-only').forEach(function(el){el.hidden=!enabled;});}
  async function checkServer(){check.disabled=true;status.className='status';label.textContent='Verificando…';try{if(!onlineHost)throw new Error('gerenciamento disponível somente em localhost');await jsonRequest('health');status.className='status online';label.textContent='Rodando';detail.textContent='O servidor está funcionando normalmente em '+location.host+'.';stop.disabled=false;setManagement(true);await loadIndexes();}catch(error){status.className='status offline';label.textContent='Com erro';detail.textContent='Não foi possível acessar o servidor: '+error.message;stop.disabled=true;setManagement(false);}finally{check.disabled=false;}}
  function closeMenus(){document.querySelectorAll('.dropdown-menu').forEach(function(menu){menu.hidden=true;});eventButton.setAttribute('aria-expanded','false');}
  function menuButton(text,handler,className){var button=document.createElement('button');button.type='button';button.textContent=text;if(className)button.className=className;button.addEventListener('click',function(e){e.stopPropagation();closeMenus();handler();});return button;}
  function openUrl(path){return '/'+path.split('/').map(encodeURIComponent).join('/');}
  function render(){count.textContent=String(events.length);list.replaceChildren();if(!events.length){list.innerHTML='<p class="empty">Nenhuma pasta com index.html foi encontrada.</p>';return;}events.forEach(function(event){var item=document.createElement('section');item.className='event-item'+(expanded.has(event.name)?' expanded':'');var head=document.createElement('div');head.className='event-head';var toggle=document.createElement('button');toggle.type='button';toggle.className='event-toggle';toggle.textContent=event.title===event.name?event.name:event.title+' · '+event.name;toggle.setAttribute('aria-expanded',expanded.has(event.name));toggle.addEventListener('click',function(){expanded.has(event.name)?expanded.delete(event.name):expanded.add(event.name);render();});var open=document.createElement('a');open.className='icon-button';open.href=openUrl(event.path);open.title='Abrir evento';open.setAttribute('aria-label','Abrir evento');open.innerHTML=icons.open;head.append(toggle,open);if(managementEnabled){var edit=document.createElement('button');edit.type='button';edit.className='icon-button';edit.title='Editar evento';edit.setAttribute('aria-label','Editar evento '+event.title);edit.innerHTML=icons.edit;edit.addEventListener('click',function(e){e.stopPropagation();openEditEventDialog(event);});var del=document.createElement('button');del.type='button';del.className='icon-button danger';del.title='Excluir evento';del.setAttribute('aria-label','Excluir evento');del.textContent='×';del.addEventListener('click',function(e){e.stopPropagation();confirmDelete('event',event);});head.append(edit,del);}item.appendChild(head);if(expanded.has(event.name)){var content=document.createElement('div');content.className='event-body';event.songs.forEach(function(song){content.appendChild(renderSong(event,song));});if(!event.songs.length){var empty=document.createElement('p');empty.className='empty';empty.textContent='Nenhuma cifra nesta pasta.';content.appendChild(empty);}if(managementEnabled){var create=document.createElement('button');create.type='button';create.className='button button-secondary create-song';create.textContent='＋ Criar nova cifra';create.addEventListener('click',function(){openSongDialog(event);});content.appendChild(create);}item.appendChild(content);}list.appendChild(item);});}
  function renderSong(event,song){var row=document.createElement('div');row.className='song-row';var link=document.createElement('a');link.className='song-link';link.href=openUrl(song.path);link.textContent=song.title;if(song.artist){var artist=document.createElement('span');artist.className='song-artist';artist.textContent=song.artist;link.appendChild(artist);}row.appendChild(link);if(managementEnabled){var wrap=document.createElement('div');wrap.className='dropdown';var more=document.createElement('button');more.type='button';more.className='icon-button';more.title='Opções da cifra';more.setAttribute('aria-label','Opções de '+song.title);more.innerHTML=icons.more;var menu=document.createElement('div');menu.className='dropdown-menu';menu.hidden=true;menu.appendChild(menuButton('Editar cifra',function(){openEditSongDialog(event,song);}));menu.appendChild(menuButton('Gerar link para capotraste',function(){openCapoDialog(event,song);}));if(song.capos.length){var heading=document.createElement('div');heading.className='capo-list-label';heading.textContent='Excluir capotraste';menu.appendChild(heading);song.capos.forEach(function(fret){menu.appendChild(menuButton('Capo na '+fret+'ª',function(){confirmDelete('capo',event,song,fret);},'danger-option'));});}menu.appendChild(menuButton('Excluir cifra',function(){confirmDelete('song',event,song);},'danger-option'));more.addEventListener('click',function(e){e.stopPropagation();var was=menu.hidden;closeMenus();menu.hidden=!was;});wrap.append(more,menu);row.appendChild(wrap);}return row;}
  function normalizeEvent(event){return {name:event.name,title:event.title||event.name,subtitle:event.subtitle||'',path:event.path,songs:(Array.isArray(event.songs)?event.songs:[]).map(function(song){song.youtube=song.youtube||'';song.capos=Array.isArray(song.capos)?song.capos:[];return song;})};}
  async function loadIndexes(){try{var data=await jsonRequest('indexes');events=(Array.isArray(data.indexes)?data.indexes:[]).filter(function(event){return event.name!=='_referencia_evento'&&event.name!=='_lixeira';}).map(normalizeEvent);render();}catch(error){count.textContent='!';list.innerHTML='<p class="empty">Não foi possível carregar as pastas: '+error.message+'</p>';}}
  function field(name,labelText,type,max,required){var box=document.createElement('div');box.className='field';var labelEl=document.createElement('label');labelEl.htmlFor='field-'+name;labelEl.textContent=labelText;var input=document.createElement('input');input.id='field-'+name;input.name=name;input.type=type||'text';input.required=required!==false;if(max)input.maxLength=max;if(name==='fret'){input.min='1';input.max='11';}box.append(labelEl,input);fields.appendChild(box);return input;}
  function showDialog(titleText,description,confirmText,submit){$('manager-title').textContent=titleText;$('manager-description').textContent=description||'';managerConfirm.textContent=confirmText;managerError.textContent='';action=submit;manager.showModal();var first=fields.querySelector('input');if(first)setTimeout(function(){first.focus();},0);}
  function openEventDialog(mode){fields.replaceChildren();var input=field(mode==='name'?'name':'date',mode==='name'?'Nome do evento':'Data do evento',mode==='name'?'text':'date',mode==='name'?30:null);showDialog(mode==='name'?'Criar evento por nome':'Criar evento por data','A nova pasta usará a estrutura de referência.','Criar',async function(){await jsonRequest('events',Object.assign({method:'POST'},body(mode==='name'?{mode:mode,name:input.value}:{mode:mode,date:input.value})));});}
  function openSongDialog(event){fields.replaceChildren();var title=field('title','Nome da música','text',100),artist=field('artist','Artista','text',100),youtube=field('youtube','Link do YouTube (opcional)','url',500,false);showDialog('Criar nova cifra','A cifra será adicionada ao index.html de '+event.name+'.','Criar cifra',async function(){await jsonRequest('songs',Object.assign({method:'POST'},body({folder:event.name,title:title.value,artist:artist.value,youtube:youtube.value})));expanded.add(event.name);});}
  function openEditSongDialog(event,song){fields.replaceChildren();var title=field('title','Nome da música','text',100),artist=field('artist','Artista','text',100),youtube=field('youtube','Link do YouTube (opcional)','url',500,false);title.value=song.title;artist.value=song.artist||'';youtube.value=song.youtube||'';showDialog('Editar cifra','Título e artista também renomeiam o arquivo e seus links.','Salvar',async function(){await jsonRequest('songs',Object.assign({method:'PUT'},body({folder:event.name,filename:song.filename,title:title.value,artist:artist.value,youtube:youtube.value})));expanded.add(event.name);});}
  function openEditEventDialog(event){fields.replaceChildren();var title=field('title','Título do evento','text',100),subtitle=field('subtitle','Subtítulo','text',100),folder=field('folder','Pasta','text',100);title.value=event.title;subtitle.value=event.subtitle;folder.value=event.name;showDialog('Editar evento','Renomear a pasta altera o endereço local do evento.','Salvar',async function(){var oldName=event.name;var data=await jsonRequest('events',Object.assign({method:'PUT'},body({folder:oldName,title:title.value,subtitle:subtitle.value,newFolder:folder.value})));expanded.delete(oldName);expanded.add(data.name);});}
  function openCapoDialog(event,song){fields.replaceChildren();var fret=field('fret','Casa do capotraste','number');showDialog('Gerar link para capotraste',song.title+' · escolha uma casa de 1 a 11.','Gerar link',async function(){await jsonRequest('capos',Object.assign({method:'POST'},body({folder:event.name,filename:song.filename,fret:Number(fret.value)})));expanded.add(event.name);});}
  function confirmDelete(kind,event,song,fret){fields.replaceChildren();var titleText,description,payload,path;if(kind==='event'){titleText='Excluir evento?';description='A pasta '+event.name+' e suas '+event.songs.length+' cifra(s) serão movidas para _lixeira.';payload={folder:event.name};path='events';}else if(kind==='song'){titleText='Excluir cifra?';description=(song.title)+' será movida para _lixeira e removida do índice.';payload={folder:event.name,filename:song.filename};path='songs';}else{titleText='Excluir link de capotraste?';description='O botão Capo na '+fret+'ª será removido do índice.';payload={folder:event.name,filename:song.filename,fret:fret};path='capos';}showDialog(titleText,description,'Excluir',async function(){await jsonRequest(path,Object.assign({method:'DELETE'},body(payload)));});}
  form.addEventListener('submit',async function(e){e.preventDefault();managerConfirm.disabled=true;managerError.textContent='';try{await action();manager.close();await loadIndexes();}catch(error){managerError.textContent=error.message;}finally{managerConfirm.disabled=false;}});
  $('manager-cancel').addEventListener('click',function(){manager.close();});
  eventButton.addEventListener('click',function(e){e.stopPropagation();var was=eventMenu.hidden;closeMenus();eventMenu.hidden=!was;eventButton.setAttribute('aria-expanded',String(was));});
  eventMenu.addEventListener('click',function(e){var mode=e.target.getAttribute('data-event-mode');if(mode){closeMenus();openEventDialog(mode);}});
  document.addEventListener('click',closeMenus);document.addEventListener('keydown',function(e){if(e.key==='Escape')closeMenus();});
  check.addEventListener('click',checkServer);
  shortcut.addEventListener('click',async function(){shortcut.disabled=true;feedback.className='feedback';feedback.textContent='Criando atalho…';try{var data=await jsonRequest('shortcut',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});feedback.textContent='Atalho criado com sucesso em '+data.path;}catch(error){feedback.className='feedback error';feedback.textContent=error.message;}finally{shortcut.disabled=false;}});
  stop.addEventListener('click',function(){shutdownDialog.showModal();});shutdownDialog.addEventListener('close',async function(){if(shutdownDialog.returnValue!=='confirm')return;stop.disabled=true;detail.textContent='Encerrando o servidor…';try{await jsonRequest('shutdown',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});status.className='status offline';label.textContent='Desligado';detail.textContent='Servidor encerrado. Você já pode fechar esta aba.';setManagement(false);setTimeout(function(){window.close();},250);}catch(error){detail.textContent='Erro ao desligar: '+error.message;stop.disabled=false;}});
  setManagement(false);checkServer();
}());
